export const news = [
  {
    title: "Carnaval Gay presenta a sus reyes para este 2021",
    author: "Javier Mendoza Daza",
    date: "Ene 13, 2021",
    img: "https://www.elheraldo.co/sites/default/files/styles/width_1180/public/articulo/2021/01/13/whatsapp_image_2021-01-13_at_6.45.21_pm.jpeg?itok=6cktiroc",
    description:
      "La junta directiva de esta fiesta en Barranquilla y el Atlántico decidió este año llevar a cabo todos sus eventos de manera virtual.",
    info: "El brillo y las lentejuelas no se verán mermados por la pandemia. La Corporación Autónoma del Carnaval Gay de Barranquilla y el Atlántico presentó este miércoles a los encargados de preservar la tradición de manera virtual. En una rueda de prensa que contó con estrictos protocolos de bioseguridad fue presentada como reina central del Carnaval Gay la joven Bárbara Trespalacios. Notablemente emocionada, la cofundadora del grupo de disfraces ‘Las negritas del swing’ reconoció tener frente a ella un enorme reto al tener que mantener vivo el espíritu de los carnavaleros a través de las diferentes plataformas digitales. De acuerdo con la soberana de las festividades de la comunidad LGBTI, esta conmemoración del Carnaval servirá para “unirnos más como población”. Naissir Abundarain será el encargado de acompañar a Bárbara Trespalacios en la tarea de llegar a cada uno de los hogares por intermedio de las plataformas digitales. Abundarain, rey Momo 2021,  ha trabajado de la mano con comunidades vulnerables en la Fundación del Mar y admite que este año la labor de los hacedores del Carnaval no será sencilla, pero cada uno de los soberanos de las carnestolendas LGBTI. Los encargados de llevar la tradición a su comunidad en todo el Atlántico son Eva Lorena Márquez y Óscar Mario Polo, quienes fueron designados como reyes departamentales del Carnaval Gay. Jairo Polo Altamar, presidente de la Corporación Autónoma del Carnaval Gay, afirma que esta es una fiesta que no se puede pausar.“Creo que las manifestaciones del Carnaval de Barranquilla no se pueden detener. Esta fiesta es muy importante para todos nosotros”, afirma. Recuerda que en septiembre empezó a estudiar las posibilidades para la realización de la fiesta y decidió entonces hacer una conmemoración virtual. Para Polo, la virtualidad se ha convertido en un escenario fundamental para el disfrute de eventos en diferentes formatos. El hacedor afirma que, por ejemplo, desde hace mucho tiempo algunos ciudadanos han estado familiarizados con el disfrute de eventos de manera remota. “Recordamos, por ejemplo, cuando hay una Batalla de Flores y la persona no puede ir, la ve por Telecaribe o por las redes sociales”, puntualiza. Tiene la esperanza de un retorno a la normalidad para que las personas puedan disfrutar de sus fiestas en la calle, compartiendo con sus seres queridos y preservando la tradición. “Esperemos con la ayuda de Dios que esto pase pronto para que la gente vuelva a disfrutar bailando en las calles. Esa es la esencia del Carnaval de Barranquilla”, manifiesta el hacedor cultural. En pocos días se revelará cuál será el calendario de eventos que tiene contemplado el Carnaval Gay. Lo que adelanta Jairo Polo es que las actividades se realizarán de forma virtual. “Estamos conversando con los demás miembros de la junta directiva y muy pronto les estaremos diciendo cómo vamos a trabajar y cuáles serán las plataformas para que la gente disfrute de nuestros eventos”, explica. Polo, quien lleva más de 32 años organizando el Carnaval Gay reconoce que este 2021 se está enfrentando al gran reto de demostrar que por medio de la virtualidad se pueden mantener vivas las tradiciones este año. Además dice que esta pandemia le ha dejado muchas enseñanzas que pueden servir como punto de partida para la construcción de una mejor sociedad. “A veces las personas creen que todo lo tienen y la verdad es que no tenemos nada. Tenemos la vida y el respaldo de Dios”. En medio de la presentación de los reyes del Carnaval Gay se hizo una reflexión que hizo eco entre los asistentes. “Nosotros hace 30 años enfrentamos una pandemia... la de la discriminación y el rechazo”, recordando aquellos tiempos en los que los miembros de la comunidad LGBTI eran fuertemente juzgados y ridiculizados por una gran parte de la sociedad por “pensar, sentir y actuar diferente”. Hoy los tiempos han cambiado y se han abierto más espacios, pero la lucha sigue, así lo reconoce Heriberto Mejía, de la Mesa LGTBI Barranquilla, quién ofreció unas palabras en medio del evento. Al finalizar la rueda de prensa, Jairo Polo hizo un llamado a la comunidad para preservar las medidas de bioseguridad para ayudar a frenar los contagios por la Covid-19 y empezar paulatinamente a volver a la normalidad. “Hay que cuidarse, lavarse las manos, portar siempre el tapabocas y actuar con responsabilidad. Que el único contagio sea de alegría”, concluyó el hacedor LGBTI.",
  },
  {
    title: "Noticia ejemplo",
    author: "autor ejemplo",
    date: "Ene 13, 2021",
    img: "https://www.elheraldo.co/sites/default/files/styles/width_1180/public/articulo/2021/01/13/whatsapp_image_2021-01-13_at_6.45.21_pm.jpeg?itok=6cktiroc",
    description: "descripcion ejemplo",
    info: "info ejemplo",
  },
  {
    title: "Noticia ejemplo",
    author: "autor ejemplo",
    date: "Ene 13, 2021",
    img: "https://www.elheraldo.co/sites/default/files/styles/width_1180/public/articulo/2021/01/13/whatsapp_image_2021-01-13_at_6.45.21_pm.jpeg?itok=6cktiroc",
    description: "descripcion ejemplo",
    info: "info ejemplo",
  },
  {
    title: "Noticia ejemplo",
    author: "autor ejemplo",
    date: "Ene 13, 2021",
    img: "https://www.elheraldo.co/sites/default/files/styles/width_1180/public/articulo/2021/01/13/whatsapp_image_2021-01-13_at_6.45.21_pm.jpeg?itok=6cktiroc",
    description: "descripcion ejemplo",
    info: "info ejemplo",
  },
  {
    title: "Noticia ejemplo",
    author: "autor ejemplo",
    date: "Ene 13, 2021",
    img: "https://www.elheraldo.co/sites/default/files/styles/width_1180/public/articulo/2021/01/13/whatsapp_image_2021-01-13_at_6.45.21_pm.jpeg?itok=6cktiroc",
    description: "descripcion ejemplo",
    info: "info ejemplo",
  },
  {
    title: "Noticia ejemplo",
    author: "autor ejemplo",
    date: "Ene 13, 2021",
    img: "https://www.elheraldo.co/sites/default/files/styles/width_1180/public/articulo/2021/01/13/whatsapp_image_2021-01-13_at_6.45.21_pm.jpeg?itok=6cktiroc",
    description: "descripcion ejemplo",
    info: "info ejemplo",
  },
  {
    title: "Noticia ejemplo",
    author: "autor ejemplo",
    date: "Ene 13, 2021",
    img: "https://www.elheraldo.co/sites/default/files/styles/width_1180/public/articulo/2021/01/13/whatsapp_image_2021-01-13_at_6.45.21_pm.jpeg?itok=6cktiroc",
    description: "descripcion ejemplo",
    info: "info ejemplo",
  },
];
